apiVersion: v1
kind: Template
metadata:
  name: mq-resources
parameters:
- name: KAFKA_VOL_SIZE
  description: Size of volumes for Kafka brokers
  value: 250Gi
- name: KAFKA_VERSION
  description: kafka version
  value: 2.7.0
- name: ZK_VOL_SIZE
  description: Size of volumes for Zookeeper nodes
  value: 50Gi
- name: KAFKA_CPU_REQUESTS
  value: 250m
- name: KAFKA_CPU_LIMITS
  value: '1'
- name: KAFKA_MEMORY_REQUESTS
  value: 4Gi
- name: KAFKA_MEMORY_LIMITS
  value: 5Gi
- name: KAFKA_NUM_REPLICAS
  value: '3'
- name: KAFKA_HEAP_OPTS_XMS
  value: 4g
- name: KAFKA_HEAP_OPTS_XMX
  value: 4g
- name: ZOOKEEPER_CPU_REQUESTS
  value: 250m
- name: ZOOKEEPER_CPU_LIMITS
  value: '1'
- name: ZOOKEEPER_MEMORY_REQUESTS
  value: 4Gi
- name: ZOOKEEPER_MEMORY_LIMITS
  value: 5Gi
- name: ZOOKEEPER_NUM_REPLICAS
  value: '3'

objects:
- apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: platform-mq
    labels:
      app: platform-mq
  spec:
    entityOperator:
      tlsSidecar:
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      topicOperator:
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
      userOperator:
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
    kafka:
      version: ${KAFKA_VERSION}
      config:
        auto.create.topics.enable: false
        log.retention.hours: 72
        offsets.topic.replication.factor: 3
        transaction.state.log.min.isr: 2
        transaction.state.log.replication.factor: 3
        num.recovery.threads.per.data.dir: 3
      jvmOptions:
        -Xms: ${KAFKA_HEAP_OPTS_XMS}
        -Xmx: ${KAFKA_HEAP_OPTS_XMX}
      listeners:
        plain: {}
        tls: {}
      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      metrics:
        # Inspired by config from Kafka 2.0.0 example rules:
        # https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-2_0_0.yml
        lowercaseOutputName: true
        rules:
        # Special cases and very specific rules
        - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
          name: kafka_server_$1_$2
          type: GAUGE
          labels:
            clientId: "$3"
            topic: "$4"
            partition: "$5"
        - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
          name: kafka_server_$1_$2
          type: GAUGE
          labels:
            clientId: "$3"
            broker: "$4:$5"
        - pattern: kafka.server<type=(.+), cipher=(.+), protocol=(.+), listener=(.+), networkProcessor=(.+)><>connections
          name: kafka_server_$1_connections_tls_info
          type: GAUGE
          labels:
            listener: "$2"
            networkProcessor: "$3"
            protocol: "$4"
            cipher: "$5"
        - pattern: kafka.server<type=(.+), clientSoftwareName=(.+), clientSoftwareVersion=(.+), listener=(.+), networkProcessor=(.+)><>connections
          name: kafka_server_$1_connections_software
          type: GAUGE
          labels:
            clientSoftwareName: "$2"
            clientSoftwareVersion: "$3"
            listener: "$4"
            networkProcessor: "$5"
        - pattern: "kafka.server<type=(.+), listener=(.+), networkProcessor=(.+)><>(.+):"
          name: kafka_server_$1_$4
          type: GAUGE
          labels:
            listener: "$2"
            networkProcessor: "$3"
        - pattern: kafka.server<type=(.+), listener=(.+), networkProcessor=(.+)><>(.+)
          name: kafka_server_$1_$4
          type: GAUGE
          labels:
            listener: "$2"
            networkProcessor: "$3"
        # Some percent metrics use MeanRate attribute
        # Ex) kafka.server<type=(KafkaRequestHandlerPool), name=(RequestHandlerAvgIdlePercent)><>MeanRate
        - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate
          name: kafka_$1_$2_$3_percent
          type: GAUGE
        # Generic gauges for percents
        - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>Value
          name: kafka_$1_$2_$3_percent
          type: GAUGE
        - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*, (.+)=(.+)><>Value
          name: kafka_$1_$2_$3_percent
          type: GAUGE
          labels:
            "$4": "$5"
        # Generic per-second counters with 0-2 key/value pairs
        - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+), (.+)=(.+)><>Count
          name: kafka_$1_$2_$3_total
          type: COUNTER
          labels:
            "$4": "$5"
            "$6": "$7"
        - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count
          name: kafka_$1_$2_$3_total
          type: COUNTER
          labels:
            "$4": "$5"
        - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count
          name: kafka_$1_$2_$3_total
          type: COUNTER
        # Generic gauges with 0-2 key/value pairs
        - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value
          name: kafka_$1_$2_$3
          type: GAUGE
          labels:
            "$4": "$5"
            "$6": "$7"
        - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value
          name: kafka_$1_$2_$3
          type: GAUGE
          labels:
            "$4": "$5"
        - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Value
          name: kafka_$1_$2_$3
          type: GAUGE
        # Emulate Prometheus 'Summary' metrics for the exported 'Histogram's.
        # Note that these are missing the '_sum' metric!
        - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count
          name: kafka_$1_$2_$3_count
          type: COUNTER
          labels:
            "$4": "$5"
            "$6": "$7"
        - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*), (.+)=(.+)><>(\d+)thPercentile
          name: kafka_$1_$2_$3
          type: GAUGE
          labels:
            "$4": "$5"
            "$6": "$7"
            quantile: "0.$8"
        - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count
          name: kafka_$1_$2_$3_count
          type: COUNTER
          labels:
            "$4": "$5"
        - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile
          name: kafka_$1_$2_$3
          type: GAUGE
          labels:
            "$4": "$5"
            quantile: "0.$6"
        - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Count
          name: kafka_$1_$2_$3_count
          type: COUNTER
        - pattern: kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile
          name: kafka_$1_$2_$3
          type: GAUGE
          labels:
            quantile: "0.$4"
      readinessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      replicas: ${{KAFKA_NUM_REPLICAS}}
      resources:
        limits:
          cpu: ${KAFKA_CPU_LIMITS}
          memory: ${KAFKA_MEMORY_LIMITS}
        requests:
          cpu: ${KAFKA_CPU_REQUESTS}
          memory: ${KAFKA_MEMORY_REQUESTS}
      tlsSidecar:
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      storage:
        deleteClaim: false
        size: ${KAFKA_VOL_SIZE}
        type: persistent-claim
    zookeeper:
      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      metrics:
        lowercaseOutputName: true
      readinessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
      replicas: ${{ZOOKEEPER_NUM_REPLICAS}}
      resources:
        limits:
          cpu: ${ZOOKEEPER_CPU_LIMITS}
          memory: ${ZOOKEEPER_MEMORY_LIMITS}
        requests:
          cpu: ${ZOOKEEPER_CPU_REQUESTS}
          memory: ${ZOOKEEPER_MEMORY_REQUESTS}
      storage:
        deleteClaim: false
        size: ${ZK_VOL_SIZE}
        type: persistent-claim
