kind: Template
apiVersion: v1
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kafka-metrics
    labels:
      app: platform-mq
  data:
    kafka-metrics-config.yml: |
      lowercaseOutputName: true
      rules:
      - labels:
          clientId: $3
          partition: $5
          topic: $4
        name: kafka_server_$1_$2
        pattern: >-
          kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+),
          partition=(.*)><>Value
        type: GAUGE
      - labels:
          broker: '$4:$5'
          clientId: $3
        name: kafka_server_$1_$2
        pattern: >-
          kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+),
          brokerPort=(.+)><>Value
        type: GAUGE
      - name: kafka_coordinator_$1_$2_$3
        pattern: 'kafka.coordinator.(\w+)<type=(.+), name=(.+)><>Value'
        type: GAUGE
      - name: kafka_$1_$2_$3_percent
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate'
        type: GAUGE
      - name: kafka_$1_$2_$3_percent
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>Value'
        type: GAUGE
      - labels:
          $4: $5
        name: kafka_$1_$2_$3_percent
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*, (.+)=(.+)><>Value'
        type: GAUGE
      - labels:
          $4: $5
          $6: $7
        name: kafka_$1_$2_$3_total
        pattern: >-
          kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+),
          (.+)=(.+)><>Count
        type: COUNTER
      - labels:
          $4: $5
        name: kafka_$1_$2_$3_total
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count'
        type: COUNTER
      - name: kafka_$1_$2_$3_total
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count'
        type: COUNTER
      - labels:
          $4: $5
          $6: $7
        name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value'
        type: GAUGE
      - labels:
          $4: $5
        name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value'
        type: GAUGE
      - name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>Value'
        type: GAUGE
      - labels:
          $4: $5
          $6: $7
        name: kafka_$1_$2_$3_count
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count'
        type: COUNTER
      - labels:
          $4: $5
          $6: $7
          quantile: 0.$8
        name: kafka_$1_$2_$3
        pattern: >-
          kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*),
          (.+)=(.+)><>(\d+)thPercentile
        type: GAUGE
      - labels:
          $4: $5
        name: kafka_$1_$2_$3_count
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count'
        type: COUNTER
      - labels:
          $4: $5
          quantile: 0.$6
        name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile'
        type: GAUGE
      - name: kafka_$1_$2_$3_count
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>Count'
        type: COUNTER
      - labels:
          quantile: 0.$4
        name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile'
        type: GAUGE

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: platform-mq
      strimzi.io/discovery: "true"
      strimzi.io/cluster: platform-mq
      strimzi.io/kind: Kafka
    name: kafka-metrics
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "9404" 
      prometheus.io/scrape: "true"  
  spec:
    ports:
      - name: tcp-prometheus
        port: 9404
        protocol: TCP
        targetPort: 9404
    selector:
      app: platform-mq
      strimzi.io/kind: Kafka
    sessionAffinity: None
    type: ClusterIP

