kind: Template
apiVersion: v1
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kafka-metrics
    labels:
      app: platform-mq
  data:
    kafka-metrics-config.yml: |
      lowercaseOutputName: true
      rules:
      - labels:
          clientId: $3
          partition: $5
          topic: $4
        name: kafka_server_$1_$2
        pattern: >-
          kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+),
          partition=(.*)><>Value
        type: GAUGE
      - labels:
          broker: '$4:$5'
          clientId: $3
        name: kafka_server_$1_$2
        pattern: >-
          kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+),
          brokerPort=(.+)><>Value
        type: GAUGE
      - pattern: kafka.server<type=(.+), clientSoftwareName=(.+), clientSoftwareVersion=(.+), listener=(.+), networkProcessor=(.+)><>connections
        name: kafka_server_$1_connections_software
        type: GAUGE
        labels:
          clientSoftwareName: "$2"
          clientSoftwareVersion: "$3"
          listener: "$4"
          networkProcessor: "$5" 
      - name: kafka_coordinator_$1_$2_$3
        pattern: 'kafka.coordinator.(\w+)<type=(.+), name=(.+)><>Value'
        type: GAUGE
      - name: kafka_$1_$2_$3_percent
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate'
        type: GAUGE
      - name: kafka_$1_$2_$3_percent
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>Value'
        type: GAUGE
      - labels:
          $4: $5
        name: kafka_$1_$2_$3_percent
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*, (.+)=(.+)><>Value'
        type: GAUGE
      - labels:
          $4: $5
          $6: $7
        name: kafka_$1_$2_$3_total
        pattern: >-
          kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+),
          (.+)=(.+)><>Count
        type: COUNTER
      - labels:
          $4: $5
        name: kafka_$1_$2_$3_total
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count'
        type: COUNTER
      - name: kafka_$1_$2_$3_total
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count'
        type: COUNTER
      - labels:
          $4: $5
          $6: $7
        name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value'
        type: GAUGE
      - labels:
          $4: $5
        name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value'
        type: GAUGE
      - name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>Value'
        type: GAUGE
      - labels:
          $4: $5
          $6: $7
        name: kafka_$1_$2_$3_count
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count'
        type: COUNTER
      - labels:
          $4: $5
          $6: $7
          quantile: 0.$8
        name: kafka_$1_$2_$3
        pattern: >-
          kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*),
          (.+)=(.+)><>(\d+)thPercentile
        type: GAUGE
      - labels:
          $4: $5
        name: kafka_$1_$2_$3_count
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count'
        type: COUNTER
      - labels:
          $4: $5
          quantile: 0.$6
        name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile'
        type: GAUGE
      - name: kafka_$1_$2_$3_count
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>Count'
        type: COUNTER
      - labels:
          quantile: 0.$4
        name: kafka_$1_$2_$3
        pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile'
        type: GAUGE
    zookeeper-metrics-config.yml: |
      # See https://github.com/prometheus/jmx_exporter for more info about JMX Prometheus Exporter metrics
      lowercaseOutputName: true
      rules:
      # replicated Zookeeper
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+)><>(\\w+)"
        name: "zookeeper_$2"
        type: GAUGE
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)><>(\\w+)"
        name: "zookeeper_$3"
        type: GAUGE
        labels:
          replicaId: "$2"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(Packets\\w+)"
        name: "zookeeper_$4"
        type: COUNTER
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(\\w+)"
        name: "zookeeper_$4"
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+), name3=(\\w+)><>(\\w+)"
        name: "zookeeper_$4_$5"
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: platform-mq
      strimzi.io/discovery: "true"
      strimzi.io/cluster: platform-mq
      strimzi.io/kind: Kafka
    name: kafka-metrics
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "9404" 
      prometheus.io/scrape: "true"  
  spec:
    ports:
      - name: tcp-prometheus
        port: 9404
        protocol: TCP
        targetPort: 9404
    selector:
      app: platform-mq
      strimzi.io/kind: Kafka
    sessionAffinity: None
    type: ClusterIP

