apiVersion: v1
kind: Template
metadata:
  name: platform-kafka-mm2
parameters:
- name: MM2_CLUSTER_NAME
  value: platform-kafka-mm2
- name: MM2_REPLICA_COUNT
  value: "1"
- name: SRC_CLUSTER_ALIAS
  value: "source-kafka-cluster"
- name: SRC_CLUSTER_BOOTSTRAP
  required: true
- name: TGT_CLUSTER_ALIAS
  value: "target-kafka-cluster"
- name: TGT_CLUSTER_BOOTSTRAP
  required: true
- name: REPLICATION_FACTOR
  value: "3"
- name: MM2_CPU_LIMIT
  value: "1"
- name: MM2_MEM_LIMIT
  value: 4Gi
- name: MM2_CPU_REQ
  value: 500m
- name: MM2_MEM_REQ
  value: 1Gi
- name: MANAGED_KAFKA_AUTH_ENDPOINT
  value: "https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token"
- name: MANAGED_KAFKA_CLIENT_ID
  value: "sample-client"
- name: AUTH_SECRET_NAME
  value: "mk-oauth-secret"
- name: AUTH_SECRET_KEY
  value: "client_secret"
objects:
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaMirrorMaker2
  metadata:
    name: ${MM2_CLUSTER_NAME}
  spec:
    logging:
      type: inline
      loggers:
        connect.root.logger.level: "DEBUG"
    clusters:
    - alias: ${SRC_CLUSTER_ALIAS}
      bootstrapServers: ${SRC_CLUSTER_BOOTSTRAP}
      tls:
        trustedCertificates:
          - secretName: platform-mq-cluster-ca-cert
            certificate: ca.crt
    - alias: ${TGT_CLUSTER_ALIAS}
      bootstrapServers: ${TGT_CLUSTER_BOOTSTRAP}
      tls:
        trustedCertificates: []
      authentication:
        type: oauth
        tokenEndpointUri: ${MANAGED_KAFKA_AUTH_ENDPOINT}
        clientId: ${MANAGED_KAFKA_CLIENT_ID}
        clientSecret:
          secretName: ${AUTH_SECRET_NAME}
          key: ${AUTH_SECRET_KEY}
    config:
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
    connectCluster: ${SRC_CLUSTER_ALIAS}
    mirrors:
      - checkpointConnector:
          config:
            checkpoints.topic.replication.factor: ${{REPLICATION_FACTOR}}
        groupsPattern: ".*"
        heartbeatConnector:
          config:
            heartbeats.topic.replication.factor: ${{REPLICATION_FACTOR}}
        sourceCluster: ${SRC_CLUSTER_ALIAS}
        sourceConnector:
          config:
            offset-syncs.topic.replication.factor: ${{REPLICATION_FACTOR}}
            replication.factor: ${{REPLICATION_FACTOR}}
            sync.topic.acls.enabled: 'false'
        targetCluster: ${TGT_CLUSTER_ALIAS}
        topicsPattern: ".*"
    replicas: ${{MM2_REPLICA_COUNT}}
    resources:
      limits:
        cpu: ${MM2_CPU_LIMIT}
        memory: ${MM2_MEM_LIMIT}
      requests:
        cpu: ${MM2_CPU_REQ}
        memory: ${MM2_MEM_REQ}
    version: 2.8.0