apiVersion: v1
kind: Template
metadata:
  name: kafka-connect
parameters:
- name: KAFKA_CONNECT_IMAGE
  value: quay.io/cloudservices/kafka-connect
- name: BOOTSTRAP_SERVERS
  value: platform-mq-kafka-bootstrap.platform-mq.svc.cluster.local:9093
objects:
- apiVersion: kafka.strimzi.io/v1beta1
  kind: KafkaConnect
  metadata:
    name: platform-kafka-connect
    labels:
      app: platform-mq
    annotations:
      strimzi.io/use-connector-resources: "true"
  spec:
    image: ${KAFKA_CONNECT_IMAGE}
    version: 2.4.0
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
    bootstrapServers: ${BOOTSTRAP_SERVERS}
    externalConfiguration:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: insights-client-metrics-strimzi-bucket
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: insights-client-metrics-strimzi-bucket
              key: aws_secret_access_key
        - name: REBUILD
          value: 'test'
    tls:
      trustedCertificates:
        - secretName: platform-mq-cluster-ca-cert
          certificate: ca.crt
    config:
      group.id: connect-cluster
      offset.storage.topic: connect-cluster-offsets
      config.storage.topic: connect-cluster-configs
      status.storage.topic: connect-cluster-status
