---
# Source: kafka-connectors/templates/template.yml
apiVersion: v1
kind: Template
metadata:
  name: kafka-connectors
objects:
- apiVersion: kafka.strimzi.io/v1alpha1
  kind: KafkaConnector
  metadata:
    name: ${S3_SINK_CONNECTOR_NAME}
    labels:
      strimzi.io/cluster: ${KAFKA_CONNECT_CLUSTER}
  spec:
    class: io.confluent.connect.s3.S3SinkConnector
    tasksMax: 3
    config:
      errors.log.enable: true
      errors.log.include.messages: true
      errors.tolerance: all
      format.class: io.confluent.connect.s3.format.json.JsonFormat
      key.converter: org.apache.kafka.connect.storage.StringConverter
      key.converter.schemas.enable: false
      flush.size: 1
      partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner
      s3.bucket.name: ${S3_SINK_BUCKET_NAME}
      s3.part.size: 5242880
      s3.region: us-east-1
      schema.compatibility: NONE
      storage.class: io.confluent.connect.s3.storage.S3Storage
      topics: ${S3_SINK_TOPICS}
      value.converter: org.apache.kafka.connect.json.JsonConverter
      value.converter.schemas.enable: false
parameters:
# Needed for processing by app-interface but not used.
- name: IMAGE_TAG
  value: latest
# Kafka cluster name will be provided at run time
- name: KAFKA_CLUSTER
  value: ""
- name: KAFKA_CONNECT_CLUSTER
  value: ""
# Name of the connector resource to create
- name: S3_SINK_CONNECTOR_NAME
  value: client-metrics-sink
# Topic to sink to s3 bucket
- name: S3_SINK_TOPICS
  value: ""
- name: S3_SINK_BUCKET_NAME
  value: ""
