apiVersion: v1
kind: Template
metadata:
  name: kafka-bridge
parameters:
- name: KAFKA_CLUSTER
  value: "platform-mq"
- name: BOOTSTRAP_SERVERS
  required: true
- name: AUTH_CLIENT_ID
  value: "username"
- name: AUTH_CLIENT_SECRET_NAME
  value: "kafka"
- name: AUTH_CLIENT_SECRET_KEY
  value: "client_secret"
- name: CPU_LIMIT
  value: "500m"
- name: MEMORY_LIMIT
  value: "512Mi"
- name: CPU_REQUEST
  value: "200m"
- name: MEMORY_REQUEST
  value: "256Mi"

objects:
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaBridge
  metadata:
    name: strimzi-bridge
    labels:
      app: platform-mq
      strimzi.io/cluster: ${KAFKA_CLUSTER}
  spec:
    replicas: 1
    bootstrapServers: ${BOOTSTRAP_SERVERS}
    tls:
      trustedCertificates: []
    authentication:
      type: scram-sha-512
      username: ${AUTH_CLIENT_ID}
      passwordSecret:
        secretName: ${AUTH_CLIENT_SECRET_NAME}
        password: ${AUTH_CLIENT_SECRET_KEY}
    http:
      port: 8080
    resources:
      requests:
        cpu: "${CPU_REQUEST}"
        memory: "${MEMORY_REQUEST}"
      limits:
        cpu: "${CPU_LIMIT}"
        memory: "${MEMORY_LIMIT}"
