apiVersion: v1
kind: Template
metadata:
  name: kafka-lag-exporter
parameters:
- name: APPSRE_ENV
  value: stage
- name: REPLICAS
  value: "1"
- name: JAVA_OPTS
  value: "-Xms64m -Xmx256m"
- name: LAG_EXPORTER_CPU_LIMIT
  value: 500m
- name: LAG_EXPORTER_MEM_LIMIT
  value: 750Mi
- name: LAG_EXPORTER_CPU_REQ
  value: 250m
- name: LAG_EXPORTER_MEM_REQ
  value: 250Mi

objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: kafka-lag-exporter
    name: kafka-lag-exporter
    annotations:
      kube-linter.io/ignore-all: "no checks needed"
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: kafka-lag-exporter
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: kafka-lag-exporter
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - kafka-lag-exporter
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - kafka-lag-exporter
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - image: quay.io/cloudservices/kafka-lag-exporter:latest
          imagePullPolicy: IfNotPresent
          name: kafka-lag-exporter
          env:
          - name: JAVA_OPTS
            value: ${JAVA_OPTS}
          ports:
          - containerPort: 8000
            name: port-8000
            protocol: TCP
          resources:
            limits:
              cpu: ${LAG_EXPORTER_CPU_LIMIT}
              memory: ${LAG_EXPORTER_MEM_LIMIT}
            requests:
              cpu: ${LAG_EXPORTER_CPU_REQ}
              memory: ${LAG_EXPORTER_MEM_REQ}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/docker/conf/
            name: exporter-config
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        - name: quay.io
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - secret:
            secretName: msk-lag-exporter-config
          name: exporter-config

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: kafka-lag-exporter
      strimzi.io/discovery: "true"
      strimzi.io/cluster: platform-mq
    name: kafka-lag-exporter
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "9404" 
      prometheus.io/scrape: "true"  
  spec:
    ports:
      - name: port-8000
        port: 8000
        protocol: TCP
        targetPort: 8000
    selector:
      app: kafka-lag-exporter
    sessionAffinity: None
    type: ClusterIP
