---
topics:
- topic_name: notifications.outbox
  partitions: 3
  replicas: 3
- topic_name: ccx.ocp.results
  partitions: 1
  replicas: 3
- topic_name: hooks.outbox
  partitions: 3
  replicas: 3
- topic_name: platform.approval
  partitions: 3
  replicas: 3
- topic_name: platform.notifications.ingress
  partitions: 3
  replicas: 3
- topic_name: platform.policies.actions-email
  partitions: 2
  replicas: 3
- topic_name: platform.policies.actions-webhook
  partitions: 2
  replicas: 3
- topic_name: platform.engine.results
  partitions: 3
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '5368709120'
- topic_name: platform.insights.rule-hits
  partitions: 50
  replicas: 3
- topic_name: platform.logging.logs
  partitions: 2
  replicas: 3
- topic_name: platform.payload-status
  partitions: 8
  replicas: 3
- topic_name: platform.receptor-controller.responses
  partitions: 3
  replicas: 3
- topic_name: platform.service-portal
  partitions: 3
  replicas: 3
- topic_name: platform.system-profile
  partitions: 32
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
- topic_name: platform.sources.event-stream
  partitions: 3
  replicas: 3
- topic_name: platform.sources.status
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.event-stream
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.operations-amazon
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.operations-azure
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.operations-ansible-tower
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.collector-ansible-tower
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.operations-openshift
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.operations-satellite
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.persister
  partitions: 10
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '500000000'
- topic_name: platform.topological-inventory.persister-output-stream
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.task-output-stream
  partitions: 3
  replicas: 3
- topic_name: platform.upload.advisor
  partitions: 64
  replicas: 3
- topic_name: platform.upload.catalog
  partitions: 3
  replicas: 3
- topic_name: platform.upload.xavier
  partitions: 3
  replicas: 3
- topic_name: platform.upload.advisor-pup
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-idle-cost-savings
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-insights-clustering
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-outlier-detection
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-volume-type-validation
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-instance-type-validation
  partitions: 3
  replicas: 3
- topic_name: platform.upload.available
  partitions: 64
  replicas: 3
- topic_name: platform.upload.buckit
  partitions: 16
  replicas: 3
- topic_name: platform.upload.compliance
  partitions: 3
  replicas: 3
- topic_name: platform.upload.hccm
  partitions: 3
  replicas: 3
- topic_name: platform.upload.leapp-reporting
  partitions: 2
  replicas: 3
- topic_name: platform.upload.mkt
  partitions: 10
  replicas: 3
- topic_name: platform.upload.qpc
  partitions: 3
  replicas: 3
- topic_name: platform.upload.rhv
  partitions: 3
  replicas: 3
- topic_name: platform.upload.testareno
  partitions: 3
  replicas: 3
- topic_name: platform.upload.tower
  partitions: 3
  replicas: 3
- topic_name: platform.upload.topological-inventory
  partitions: 3
  replicas: 3
- topic_name: platform.upload.validation
  partitions: 24
  replicas: 3
- topic_name: vulnerability.evaluator.upload
  partitions: 24
  replicas: 3
- topic_name: vulnerability.evaluator.recalc
  partitions: 24
  replicas: 3
- topic_name: platform.inventory.events
  partitions: 64
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact,delete'
  - name: min.compaction.lag.ms
    value: '3600000'
  - name: retention.bytes
    value: '5368709120'
  - name: retention.ms
    value: '2678400000'
- topic_name: platform.inventory.events-test-synchronizer
  partitions: 64
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact,delete'
  - name: min.compaction.lag.ms
    value: '3600000'
  - name: retention.bytes
    value: '536870912'
  - name: retention.ms
    value: '2678400000'
- topic_name: platform.cyndi.dlq
  partitions: 1
  replicas: 3
  topic_configs:
    - name: retention.bytes
      value: '5368709120'
    - name: retention.ms
      value: '2678400000'
- topic_name: platform.rhsm-conduit.tasks
  partitions: 24
  replicas: 3
- topic_name: platform.testing.rhsm-conduit-tasks
  partitions: 24
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '2684354560'
- topic_name: platform.inventory.host-ingress
  partitions: 20
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '2684354560'
- topic_name: platform.inventory.host-ingress-p1
  partitions: 20
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '2684354560'
- topic_name: ruledev.nomination
  partitions: 2
  replicas: 3
- topic_name: patchman.evaluator.upload
  partitions: 64
  replicas: 3
- topic_name: patchman.evaluator.recalc
  partitions: 64
  replicas: 3
- topic_name: platform.rhsm-subscriptions.tasks
  partitions: 24
  replicas: 3
- topic_name: platform.remediation-updates.advisor
  partitions: 3
  replicas: 3
- topic_name: platform.remediation-updates.patch
  partitions: 3
  replicas: 3
- topic_name: platform.remediation-updates.vulnerability
  partitions: 3
  replicas: 3
- topic_name: platform.remediation-updates.compliance
  partitions: 3
  replicas: 3
- topic_name: platform.catalog.persister
  partitions: 3
  replicas: 3
- topic_name: platform.catalog-inventory.task-output-stream
  partitions: 3
  replicas: 3
- topic_name: platform.upload.playbook
  partitions: 3
  replicas: 3
- topic_name: ccx.ocp.dlq
  partitions: 1
  replicas: 3
