---
topics:
- topic_name: notifications.outbox
  partitions: 3
  replicas: 3
- topic_name: ccx.ocp.results
  partitions: 1
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '259200000'
- topic_name: ccx.aggregator.dead.letter.queue
  partitions: 1
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '259200000'
- topic_name: ccx.data.pipeline.dead.letter.queue
  partitions: 1
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '259200000'
- topic_name: ccx.sha.extractor.dead.letter.queue
  partitions: 1
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '259200000'
- topic_name: ccx.image.sha.results
  partitions: 2
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '259200000'
- topic_name: ccx.dvo.results
  partitions: 1
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '259200000'
- topic_name: hooks.outbox
  partitions: 6
  replicas: 3
- topic_name: platform.approval
  partitions: 3
  replicas: 3
- topic_name: platform.notifications.aggregation
  partitions: 2
  replicas: 3
- topic_name: platform.notifications.ingress
  partitions: 6
  replicas: 3
- topic_name: platform.policies.actions-email
  partitions: 2
  replicas: 3
- topic_name: platform.policies.actions-webhook
  partitions: 2
  replicas: 3
- topic_name: platform.policies.history
  partitions: 2
  replicas: 3
- topic_name: platform.provisioning.internal.availability-check
  partitions: 1
  replicas: 3
- topic_name: platform.engine.results
  partitions: 6
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '5368709120'
- topic_name: platform.insights.rule-hits
  partitions: 50
  replicas: 3
- topic_name: platform.logging.logs
  partitions: 2
  replicas: 3
- topic_name: platform.payload-status
  partitions: 8
  replicas: 3
- topic_name: platform.receptor-controller.responses
  partitions: 3
  replicas: 3
- topic_name: platform.service-portal
  partitions: 3
  replicas: 3
- topic_name: platform.system-profile
  partitions: 32
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
- topic_name: platform.sources.event-stream
  partitions: 6
  replicas: 3
- topic_name: platform.sources.status
  partitions: 3
  replicas: 3
- topic_name: platform.sources.operations-ansible-tower
  partitions: 3
  replicas: 3
- topic_name: platform.sources.operations-satellite
  partitions: 3
  replicas: 3
- topic_name: platform.topological-inventory.operations-satellite
  partitions: 3
  replicas: 3
- topic_name: platform.tower-analytics.data-exporter
  partitions: 10
  replicas: 3
- topic_name: platform.upload.advisor
  partitions: 64
  replicas: 3
- topic_name: platform.upload.catalog
  partitions: 3
  replicas: 3
- topic_name: platform.upload.xavier
  partitions: 3
  replicas: 3
- topic_name: platform.upload.advisor-pup
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-idle-cost-savings
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-insights-clustering
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-outlier-detection
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-volume-type-validation
  partitions: 3
  replicas: 3
- topic_name: platform.upload.aiops-instance-type-validation
  partitions: 3
  replicas: 3
- topic_name: platform.upload.available
  partitions: 64
  replicas: 3
- topic_name: platform.upload.buckit
  partitions: 16
  replicas: 3
- topic_name: platform.upload.compliance
  partitions: 3
  replicas: 3
- topic_name: platform.upload.hccm
  partitions: 3
  replicas: 3
- topic_name: platform.upload.leapp-reporting
  partitions: 2
  replicas: 3
- topic_name: platform.upload.mkt
  partitions: 10
  replicas: 3
- topic_name: platform.upload.pinakes
  partitions: 10
  replicas: 3
- topic_name: platform.upload.qpc
  partitions: 3
  replicas: 3
- topic_name: platform.upload.resource-optimization
  partitions: 3
  replicas: 3
- topic_name: platform.upload.rhv
  partitions: 3
  replicas: 3
- topic_name: platform.upload.testareno
  partitions: 3
  replicas: 3
- topic_name: platform.upload.tower
  partitions: 10
  replicas: 3
- topic_name: platform.upload.validation
  partitions: 24
  replicas: 3
- topic_name: platform.upload.malware-detection
  partitions: 3
  replicas: 3
- topic_name: vulnerability.evaluator.upload
  partitions: 24
  replicas: 3
- topic_name: vulnerability.evaluator.recalc
  partitions: 24
  replicas: 3
- topic_name: vulnerability.evaluator.results
  partitions: 24
  replicas: 3
- topic_name: vulnerability.grouper.inventory.upload
  partitions: 24
  replicas: 3
- topic_name: vulnerability.grouper.advisor.upload
  partitions: 24
  replicas: 3
- topic_name: vulnerability.listener.ingress
  partitions: 3
  replicas: 3
- topic_name: platform.upload.announce
  partitions: 64
  replicas: 3
- topic_name: platform.inventory.events
  partitions: 64
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact,delete'
  - name: min.compaction.lag.ms
    value: '3600000'
  - name: retention.bytes
    value: '6442450944'
  - name: retention.ms
    value: '2678400000'
- topic_name: platform.inventory.events-test-synchronizer
  partitions: 64
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact,delete'
  - name: min.compaction.lag.ms
    value: '3600000'
  - name: retention.bytes
    value: '536870912'
  - name: retention.ms
    value: '2678400000'
- topic_name: platform.cyndi.dlq
  partitions: 1
  replicas: 3
  topic_configs:
    - name: retention.bytes
      value: '5368709120'
    - name: retention.ms
      value: '2678400000'
- topic_name: platform.rhsm-conduit.tasks
  partitions: 24
  replicas: 3
- topic_name: platform.testing.rhsm-conduit-tasks
  partitions: 24
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '2684354560'
- topic_name: platform.inventory.host-ingress
  partitions: 20
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '2684354560'
- topic_name: platform.inventory.host-ingress-p1
  partitions: 20
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '86400000'
  - name: retention.bytes
    value: '2684354560'
- topic_name: platform.inventory.system-profile
  partitions: 3
  replicas: 3
- topic_name: ruledev.nomination
  partitions: 2
  replicas: 3
- topic_name: patchman.evaluator.upload
  partitions: 64
  replicas: 3
- topic_name: patchman.evaluator.recalc
  partitions: 64
  replicas: 3
- topic_name: platform.export.requests
  partitions: 3
  replicas: 3
- topic_name: platform.rhsm-subscriptions.tasks
  partitions: 24
  replicas: 3
- topic_name: platform.remediation-updates.advisor
  partitions: 6
  replicas: 3
- topic_name: platform.remediation-updates.patch
  partitions: 3
  replicas: 3
- topic_name: platform.remediation-updates.vulnerability
  partitions: 3
  replicas: 3
- topic_name: platform.remediation-updates.compliance
  partitions: 3
  replicas: 3
- topic_name: platform.catalog.persister
  partitions: 3
  replicas: 3
- topic_name: platform.catalog-inventory.task-output-stream
  partitions: 3
  replicas: 3
- topic_name: platform.upload.playbook
  partitions: 16
  replicas: 3
- topic_name: ccx.ocp.dlq
  partitions: 1
  replicas: 3
- topic_name: platform.playbook-dispatcher.runner-updates
  partitions: 16
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact,delete'
  - name: min.compaction.lag.ms
    value: '3600000'
  - name: retention.bytes
    value: '1073741824'
  - name: retention.ms
    value: '86400000'
- topic_name: platform.playbook-dispatcher.runs
  partitions: 16
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact,delete'
  - name: min.compaction.lag.ms
    value: '3600000'
  - name: retention.bytes
    value: '1073741824'
  - name: retention.ms
    value: '2678400000'
- topic_name: platform.playbook-dispatcher.run-hosts
  partitions: 16
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact,delete'
  - name: min.compaction.lag.ms
    value: '3600000'
  - name: retention.bytes
    value: '1073741824'
  - name: retention.ms
    value: '2678400000'
- topic_name: platform.rhsm-subscriptions.metering-tasks
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.metering-rhel-tasks
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.openshift-metering-tasks
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.tally
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.capacity-reconcile
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.subscription-prune
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.subscription-sync
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.offering-sync
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.billable-usage
  partitions: 24
  replicas: 3
- topic_name: platform.sources.superkey-requests
  partitions: 3
  replicas: 3
- topic_name: platform.insights.client-metrics
  partitions: 3
  replicas: 3
- topic_name: storage-topic
  partitions: 3
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact'
- topic_name: global-id-topic
  partitions: 3
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact'
- topic_name: platform.cloud-connector.rhc-message-ingress
  partitions: 24
  replicas: 3
- topic_name: platform.edge.fleetmgmt.image-build
  partitions: 3
  replicas: 3
- topic_name: platform.edge.fleetmgmt.device-update
  partitions: 3
  replicas: 3
- topic_name: platform.notifications.tocamel
  partitions: 3
  replicas: 3
- topic_name: platform.notifications.fromcamel
  partitions: 3
  replicas: 3
- topic_name: heartbeats
  partitions: 1
  replicas: 3
- topic_name: mirrormaker2-cluster-configs
  partitions: 1
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact'
- topic_name: mirrormaker2-cluster-offsets
  partitions: 1
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact'
- topic_name: mirrormaker2-cluster-status
  partitions: 1
  replicas: 3
  topic_configs:
  - name: cleanup.policy
    value: 'compact'
- topic_name: source-kafka-cluster.checkpoints.internal
  partitions: 1
  replicas: 3
- topic_name: platform.content-sources.introspect
  partitions: 3
  replicas: 3
- topic_name: platform.rbac.sync
  partitions: 10
  replicas: 3
- topic_name: platform.chrome
  partitions: 10
  replicas: 3
- topic_name: hccm.ros.events
  partitions: 30
  replicas: 3
  topic_configs:
  - name: retention.ms
    value: '604800000'
  - name: retention.bytes
    value: '1073741824'
- topic_name: rosocp.kruize.recommendations
  partitions: 3
  replicas: 3
- topic_name: rosocp.kruize.experiments
  partitions: 3
  replicas: 3
- topic_name: platform.upload.runtimes-java-general
  partitions: 3
  replicas: 3
- topic_name: platform.rhsm-subscriptions.service-instance-ingress
  partitions: 24
  replicas: 3
- topic_name: platform.rhsm-subscriptions.service-instance-ingress.dlt
  partitions: 24
  replicas: 3
