apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: platform-mq-dev
spec:
  limits:
  - max:
      cpu: 1800m
      memory: 6Gi
    min:
      cpu: 100m
      memory: 50Mi
    type: Pod
  - default:
      cpu: 300m
      memory: 200Mi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
    maxLimitRequestRatio:
      cpu: "10"
    type: Container
