{
 "title": "ConsoleDot MSK Stage",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  { "title": "Health Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aws_kafka_cpu_system_sum{cluster_name=\"consoledot-stage\"})",
     "legendFormat": "__auto",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "ActiveControllerCount", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(ActiveControllerCount) FROM \"AWS/Kafka\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_kafka_global_partition_count_sum{cluster_name=\"consoledot-stage\"}",
     "legendFormat": "__auto",
     "metricName": "PartitionCount",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "PartitionCount", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(PartitionCount) FROM \"AWS/Kafka\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_kafka_under_replicated_partitions_sum{cluster_name=\"consoledot-stage\"})",
     "legendFormat": "__auto",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "UnderReplicatedPartitions", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(UnderReplicatedPartitions) FROM \"AWS/Kafka\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Partitions Offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_kafka_offline_partitions_count_sum{cluster_name=\"consoledot-stage\"}",
     "legendFormat": "__auto",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "OfflinePartitionsCount", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(OfflinePartitionsCount) FROM \"AWS/Kafka\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Resource Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aws_kafka_memory_used_sum{cluster_name=\"consoledot-stage\"}",
       "label": "Broker",
       "legendFormat": "Broker {{broker_id}}",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "MemoryUsed", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(MemoryUsed) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "User CPU per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_kafka_cpu_user_sum{cluster_name=\"consoledot-stage\"}",
       "label": "CPU User on Broker",
       "legendFormat": "Broker {{broker_id}} %User",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "CpuUser", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(CpuUser) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Disk Usage per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_kafka_kafka_data_logs_disk_used_sum{cluster_name=\"consoledot-stage\"}",
       "label": "Broker",
       "legendFormat": "Logs Dir Used Broker {{broker_id}}",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "KafkaDataLogsDiskUsed", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(KafkaDataLogsDiskUsed) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "label": "Broker",
       "metricName": "BytesInPerSec",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "BytesInPerSec", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(BytesInPerSec) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Bytes Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "label": "Broker",
       "metricName": "BytesInPerSec",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "BytesOutPerSec", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(BytesOutPerSec) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Zookeeper Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(aws_kafka_zoo_keeper_request_latency_ms_mean_sum{cluster_name=\"consoledot-stage\"}) by (broker_id)",
       "label": "Broker",
       "legendFormat": "Broker {{broker_id}} Latency",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "ZooKeeperRequestLatencyMsMean", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(ZooKeeperRequestLatencyMsMean) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Lag Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Lag by Group",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "max(aws_kafka_max_offset_lag_maximum{cluster_name=\"consoledot-stage\", consumer_group!~\".*amazon.*\"}) by (consumer_group, topic)",
       "legendFormat": "{{topic}} -- Group {{consumer_group}}",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Consumer Group", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "SumOffsetLag", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(SumOffsetLag) FROM \"AWS/Kafka\" GROUP BY \"Consumer Group\"",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}