{
 "title": "ConsoleDot RHOSAK",
 "description": "Metrics for ConsoleDot RHOSAK Clusters",
 "tags": [
  "kafka",
  "platform-health"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Topic",
    "query": {
     "query": "query_result(kafka_topic:kafka_log_log_size:sum)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(kafka_namespace:haproxy_server_bytes_in_total:rate5m)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Topics",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_topic:kafka_topic_partitions:count{job=~\"$Cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Byte Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "kafka_namespace:haproxy_server_bytes_in_total:rate5m{job=~\"$Cluster\"}",
       "legendFormat": "Produce Rate Past 5m"
      },
      {
       "expr": "kafka_namespace:haproxy_server_bytes_out_total:rate5m{job=~\"$Cluster\"}",
       "legendFormat": "Consume Rate Past 5m"
      }
     ]
    },
    {
     "title": "Total Partitions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_topic:kafka_topic_partitions:sum{job=~\"$Cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Active Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_namespace:kafka_server_socket_server_metrics_connection_count:sum",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "New Connection Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "kafka_namespace:kafka_server_socket_server_metrics_connection_creation_rate:sum{job=~\"$Cluster\"}",
       "legendFormat": "Connections Created per Second"
      }
     ]
    }
   ]
  },
  {
   "title": "Broker (Kafka Server) Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Quota Used",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_broker_quota_totalstorageusedbytes{job=~\"$Cluster\"}/kafka_broker_quota_softlimitbytes{job=~\"$Cluster\"}",
       "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    },
    {
     "title": "Offline Partitions",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_offline_partitions_count{job=~\"$Cluster\"}",
       "legendFormat": "{{ statefulset_kubernetes_io_pod_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Topic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Incoming Data Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_topic:kafka_server_brokertopicmetrics_bytes_in_total:rate5m{topic=~\"$Topic\", job=~\"$Cluster\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Data Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_topic:kafka_server_brokertopicmetrics_bytes_out_total:rate5m{topic=~\"$Topic\", job=~\"$Cluster\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Incoming Messages Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_topic:kafka_server_brokertopicmetrics_messages_in_total:rate5m{topic=~\"$Topic\", job=~\"$Cluster\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consumer Groups/Lag Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Lag by Topic and Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{cluster_name=\"RHOSAK\", topic=~\"$Topic\"}) by (group, topic)",
     "legendFormat": "{{topic}} -- {{group}}"
    }
   ]
  }
 ]
}