{
 "title": "ConsoleDot MSK",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "query": "stage : s, prod : p" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(aws_kafka_bytes_in_per_sec_average,cluster_name)"
    }
   },
   { "name": "lag_datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Health Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aws_kafka_kafka_data_logs_disk_used_average{cluster_name=\"$cluster\"})",
     "legendFormat": "__auto",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "ActiveControllerCount", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(ActiveControllerCount) FROM \"AWS/Kafka\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_kafka_global_partition_count_sum{cluster_name=\"$cluster\"}",
     "legendFormat": "__auto",
     "metricName": "PartitionCount",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "PartitionCount", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(PartitionCount) FROM \"AWS/Kafka\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_kafka_under_replicated_partitions_sum{cluster_name=\"$cluster\"})",
     "legendFormat": "__auto",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "UnderReplicatedPartitions", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(UnderReplicatedPartitions) FROM \"AWS/Kafka\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Partitions Offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_kafka_offline_partitions_count_sum{cluster_name=\"$cluster\"}",
     "legendFormat": "__auto",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "OfflinePartitionsCount", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(OfflinePartitionsCount) FROM \"AWS/Kafka\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_kafka_client_connection_count_maximum{cluster_name=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory After GC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_kafka_heap_memory_after_gc_average{cluster_name=\"$cluster\"}",
       "label": "Broker",
       "legendFormat": "Broker {{broker_id}}",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "MemoryUsed", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(MemoryUsed) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "CPU per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_kafka_cpu_system_maximum{cluster_name=\"$cluster\"}",
       "label": "CPU User on Broker",
       "legendFormat": "Broker {{broker_id}} %System",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "CpuUser", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(CpuUser) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Average"
      },
      {
       "expr": "aws_kafka_cpu_user_maximum{cluster_name=\"$cluster\"}",
       "legendFormat": "Broker {{broker_id}} %User"
      }
     ]
    },
    {
     "title": "Disk Usage per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_kafka_kafka_data_logs_disk_used_sum{cluster_name=\"$cluster\"}",
       "label": "Broker",
       "legendFormat": "Logs Dir Used Broker {{broker_id}}",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "KafkaDataLogsDiskUsed", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(KafkaDataLogsDiskUsed) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(aws_kafka_bytes_in_per_sec_average{cluster_name=\"$cluster\"}) by (broker_id)",
     "legendFormat": "Broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(aws_kafka_bytes_out_per_sec_average{cluster_name=\"$cluster\"}) by (broker_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_kafka_connection_count_maximum{cluster_name=\"$cluster\"})",
     "legendFormat": "Total Connection Count"
    },
    {
     "expr": "sum(aws_kafka_client_connection_count_maximum{cluster_name=\"$cluster\"}) by (client_authentication, broker_id)",
     "legendFormat": "{{client_authentication}} Broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Zookeeper Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aws_kafka_zoo_keeper_request_latency_ms_mean_sum{cluster_name=\"$cluster\"}",
     "label": "Broker",
     "legendFormat": "Broker {{broker_id}}",
     "metricQueryType": 1,
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Broker ID", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "ZooKeeperRequestLatencyMsMean", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(ZooKeeperRequestLatencyMsMean) FROM \"AWS/Kafka\" GROUP BY \"Broker ID\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lag Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Lag by Group",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_group_lag{}) by (topic, group)",
       "legendFormat": "Group: {{group}} Topic: {{topic}}",
       "metricQueryType": 1,
       "namespace": "AWS/Kafka",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/Kafka", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "Consumer Group", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "SumOffsetLag", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(SumOffsetLag) FROM \"AWS/Kafka\" GROUP BY \"Consumer Group\"",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}