apiVersion: v1
kind: Template
metadata:
  name: kafka-topics
objects:
{{- range $t, $topic := .Values.topics }}
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaTopic
  metadata:
    name: {{ $topic.topic_name }}
    labels:
      strimzi.io/cluster: ${KAFKA_CLUSTER}
  spec:
    partitions: {{ $topic.partitions }}
    replicas: {{ $topic.replicas }}
    topicName: {{ $topic.topic_name }}
    config:
      min.insync.replicas: 2
    {{- $retention := false }}
    {{- if $topic.topic_configs }}
      {{- range $c, $config := $topic.topic_configs }}
      {{- if contains "retention" $config.name }}
        {{- $retention = true }}
      {{- end }}
      {{ $config.name }}: "{{ $config.value }}"
      {{- end }}
    {{- end }}
    {{- if not $retention }}
      retention.ms: "259200000"
    {{- end}}
{{- end }}
parameters:
# Needed for processing by app-interface but not used.
- name: IMAGE_TAG
  value: latest
# Kafka cluster name will be provided at run tim
- name: KAFKA_CLUSTER
  value: ""
