{
  "type": "record",
  "name": "testdata",
  "namespace": "platform.testing",
  "fields": [
    {
      "name": "rh_account",
      "doc": "The account number used to upload.",
      "type": "string"
    },
    {
      "name": "principal",
      "doc": "The uploading org ID",
      "type": "string"
    },
    {
      "name": "validation",
      "doc": "Validation status of the object",
      "type": "boolean"
    },
    {
      "name": "payload_id",
      "doc": "Unique ID provided to the payload created by 3Scale. This ID will be used for the life of the object.",
      "type": "string"
    },
    {
      "name": "hash",
      "doc": "Legacy key name. Provides the same UID as payload_id. Will be deprecated.",
      "type": ["null", "string"]
    },
    {
      "name": "size",
      "doc": "Size of the payload in bytes",
      "type": "int"
    },
    {
      "name": "service",
      "doc": "The name of the service expected to validate the object",
      "type": "string"
    },
    {
      "name": "url",
      "doc": "URL from which the payload can be downloaded",
      "type": "string"
    }
  ]
}
